version: '3.8'
services:
  apigateway:
    build: ./PerfectPick_ag
    container_name: apigateway
    ports:
      - "9000:9000"
    networks:
      - myalltimenetwork

networks:
  perfectpicknetwork:
    external: true

